services:

  # ============= Open Code =============
  opencode:
    build:
      context: .
      dockerfile: Dockerfile
    image: img_code_opencode
    container_name: ctr_code_opencode
    working_dir: /workspace
    tty: true
    stdin_open: true
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      - TZ=${TZ}
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./:/workspace:rw,uid=${HOST_UID},gid=${HOST_GID}
      - .config/opencode:/home/node/.config/opencode  # Mapeo del archivo de config
    depends_on:
      - ollama
    command: >
      /bin/bash -c "
        if [ ! -d node_modules/opencode-ai ]; then
          echo 'Instalando OpenCode (local)...' &&
          npm install --no-audit --no-fund opencode-ai;
        fi &&
        exec bash
      "
    networks:
      - net_code

  # ============= Ollama =============
  ollama:
    image: ollama/ollama:0.17.7
    container_name: ctr_code_ollama
    restart: unless-stopped
    environment:
      # - OLLAMA_ORIGINS=${FRONT_URL}
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=15m
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL}
      - OLLAMA_NUM_THREADS=${OLLAMA_NUM_THREADS}
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH}
      - OLLAMA_BATCH_SIZE=${OLLAMA_BATCH_SIZE}
      - OLLAMA_USE_MMAP=${OLLAMA_USE_MMAP}
      - OLLAMA_VULKAN=${OLLAMA_VULKAN}
    expose:
      - "11434"
    volumes:
      - ${HOST_BASE_PATH}/Docker/volumes/vol_ollama/_data:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: ${OLLAMA_CPU_LIMIT}
          memory: ${OLLAMA_RAM_LIMIT}
    networks:
      - net_code

# ============= NETWORK =============
networks:
  net_code:
    name: net_code
    driver: bridge